# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'voiceBroadcast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'SVProgressHUD', '~> 2.0.3'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'MJRefresh', '~> 3.1.12’
pod 'Masonry', '~> 1.0.2'

  # Pods for voiceBroadcast

end
